SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spInsertVendedor]
    (
        @CODVEND CHAR(4),
		@NOMVEND VARCHAR(60),
		@APEVEND VARCHAR(80),
		@EMAVEND VARCHAR(70),
		@CELVEND CHAR(9),
		@DIRVEND VARCHAR(70),
		@ESTVEND CHAR(1)
    )
AS
BEGIN
    SET NOCOUNT ON
    BEGIN TRAN /* TRANSACCIONES */
    BEGIN TRY
        IF (SELECT COUNT(*) FROM VENDEDOR WHERE VENDEDOR.CELVEND = @CELVEND) = 1
            ROLLBACK TRAN;
        ELSE 
            INSERT INTO VENDEDOR
            (CODVEND, NOMVEND, APEVEND, CELVEND, EMAVEND, DIRVEND, ESTVEND)
            VALUES
            (@CODVEND, (@NOMVEND), (@APEVEND), @CELVEND, 
            LOWER(@EMAVEND), @DIRVEND, @ESTVEND)
            COMMIT TRAN
    END TRY
    BEGIN CATCH
        SELECT 'Este vendedor ya ha sido registrado' AS ERROR
        IF @@TRANCOUNT > 0 ROLLBACK TRAN;
    END CATCH
END
GO
