SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spInsertCliente]
    (
        @CODCLI CHAR(4),
		@NOMCLI VARCHAR(60),
		@APECLI VARCHAR(80),
		@EMACLI VARCHAR(80),
		@CELCLI CHAR(9),
		@DIRCLI VARCHAR(70),
		@ESTCLI CHAR(1)
    )
AS
BEGIN
    SET NOCOUNT ON
    BEGIN TRAN /* TRANSACCIONES */
    BEGIN TRY
        IF (SELECT COUNT(*) FROM CLIENTE WHERE CLIENTE.CELCLI = @CELCLI) = 1
            ROLLBACK TRAN;
        ELSE 
            INSERT INTO CLIENTE
            (CODCLI, NOMCLI, APECLI, CELCLI, EMACLI, DIRCLI, ESTCLI)
            VALUES
            (@CODCLI, (@NOMCLI), (@APECLI), @CELCLI, 
            LOWER(@EMACLI), @DIRCLI, @ESTCLI)
            COMMIT TRAN
    END TRY
    BEGIN CATCH
        SELECT 'Este cliente ya ha sido registrado' AS ERROR
        IF @@TRANCOUNT > 0 ROLLBACK TRAN;
    END CATCH
END
GO
