SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spInsertProveedor]
    (
		@CODPROV CHAR(5),
		@RAZSOCPROV VARCHAR(90),
		@RUCPROV CHAR(11),
		@EMAPROV VARCHAR(70),
		@ESTPROV CHAR(1)
    )
AS
BEGIN
    SET NOCOUNT ON
    BEGIN TRAN /* TRANSACCIONES */
    BEGIN TRY
        IF (SELECT COUNT(*) FROM PROVEEDOR WHERE PROVEEDOR.RUCPROV = @RUCPROV) = 1
            ROLLBACK TRAN;
        ELSE 
            INSERT INTO PROVEEDOR
            (CODPROV, RAZSOCPROV, RUCPROV, EMAPROV, ESTPROV)
            VALUES
            (@CODPROV, @RAZSOCPROV,(@RUCPROV),(@EMAPROV), @ESTPROV)
            COMMIT TRAN
    END TRY
    BEGIN CATCH
        SELECT 'Este proveedor ya ha sido registrado' AS ERROR
        IF @@TRANCOUNT > 0 ROLLBACK TRAN;
    END CATCH
END
GO
