CREATE TABLE [dbo].[VENTADETALLE]
(
[IDVENDET] [int] NOT NULL IDENTITY(1, 1),
[CODVEN] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CODPRO] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CANTPRO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTADETALLE] ADD CONSTRAINT [IDVENDET_PK] PRIMARY KEY CLUSTERED ([CANTPRO]) ON [PRIMARY]
GO
