CREATE TABLE [dbo].[PROVEEDOR]
(
[CODPROV] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RAZSOCPROV] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RUCPROV] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMAPROV] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ESTPROV] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROVEEDOR] ADD CONSTRAINT [CODPROV] PRIMARY KEY CLUSTERED ([ESTPROV]) ON [PRIMARY]
GO
