CREATE TABLE [dbo].[CLIENTE]
(
[CODCLI] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOMCLI] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[APECLI] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMACLI] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CELCLI] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIRCLI] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ESTCLI] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTE] ADD CONSTRAINT [CODCLI_PK] PRIMARY KEY CLUSTERED ([ESTCLI]) ON [PRIMARY]
GO
