CREATE TABLE [dbo].[COMPRA]
(
[CODCOM] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECCOM] [datetime] NULL,
[CODVEND] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CODPROV] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ESTCOM] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COMPRA] ADD CONSTRAINT [CODCOM_PK] PRIMARY KEY CLUSTERED ([ESTCOM]) ON [PRIMARY]
GO
