CREATE TABLE [dbo].[VENTA]
(
[CODVEN] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECVEN] [datetime] NULL,
[CODCLI] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CODVEND] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ESTVEN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [CODVEN_PK] PRIMARY KEY CLUSTERED ([ESTVEN]) ON [PRIMARY]
GO
