CREATE TABLE [dbo].[COMPRADETALLE]
(
[IDCOMDET] [int] NOT NULL IDENTITY(1, 1),
[CODCOM] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CODPRO] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CANTPRO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COMPRADETALLE] ADD CONSTRAINT [IDCOMDET_PK] PRIMARY KEY CLUSTERED ([CANTPRO]) ON [PRIMARY]
GO
