CREATE TABLE [dbo].[PRODUCTO]
(
[CODPRO] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCPRO] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CATPRO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PREPRO] [decimal] (8, 2) NULL,
[STOCKPRO] [int] NULL,
[ESTPRO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [CODPRO] PRIMARY KEY CLUSTERED ([ESTPRO]) ON [PRIMARY]
GO
