CREATE TABLE [dbo].[VENDEDOR]
(
[CODVEND] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOMVEND] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[APEVEND] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMAVEND] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CELVEND] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIRVEND] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ESTVEND] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENDEDOR] ADD CONSTRAINT [CODVEND_PK] PRIMARY KEY CLUSTERED ([ESTVEND]) ON [PRIMARY]
GO
